# Generated by Django 4.2.8 on 2023-12-15 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('title', models.PositiveSmallIntegerField(choices=[(1, 'Team Lead'), (2, 'Mid Lead'), (3, 'Junior')], default=3)),
                ('gender', models.IntegerField(choices=[(1, 'male'), (2, 'female')])),
                ('salary', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('departman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Personel', to='personel.departman')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Personel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
