# Generated by Django 4.2.8 on 2023-12-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='title',
            field=models.CharField(choices=[('Team_Lead', 'Team Lead'), ('Mid_Lead', 'Mid Lead'), ('Junior', 'Junior')], default=3, max_length=10),
        ),
    ]
