# Generated by Django 4.2.8 on 2023-12-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0002_alter_personel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='personel',
            name='title',
            field=models.CharField(choices=[('TeamLead', 'Team Lead'), ('MidLead', 'Mid Lead'), ('Junior', 'Junior')], default='Junior', max_length=10),
        ),
    ]
